In [1]:
import pandas as pd
import numpy as np

In [2]:
from google.colab import files
uploaded = files.upload()

Saving AP_SAT_Data.csv to AP_SAT_Data.csv


In [3]:
filename = list(uploaded.keys())[0]

In [4]:
df = pd.read_csv(filename)

In [5]:
df

DBN                                         SchoolName  \
0    01M448                       UNIVERSITY NEIGHBORHOOD H.S.   
1    01M515                                LOWER EASTSIDE PREP   
2    01M539                     NEW EXPLORATIONS SCI,TECH,MATH   
3    02M300  Urban Assembly School of Design and Construction,   
4    02M305  Urban Assembly Academy of Government and Law, The   
..      ...                                                ...   
143  31R460                                 SUSAN E. WAGNER HS   
144  31R605                         STATEN ISLAND TECHNICAL HS   
145  32K545                      EBC-HS FOR PUB SERVICE (BUSH)   
146  32K552                          Academy of Urban Planning   
147  32K556  Bushwick Leaders High School for Academic Exce...   

    No_AP_TestTakers Total_Exam_Taken No_Exam_Passed  SAT_Math_Score  
0                 39               49             10             419  
1                 24               26             24             532  
2                255              377            191             583  
3                 99              117             10             446  
4                 25               37             15             406  
..               ...              ...            ...             ...  
143              279              408            175             482  
144              528              905            809             673  
145               47               64             13             390  
146               76              100             10             361  
147               34               35             18             345  

[148 rows x 6 columns]

In [6]:
df.dtypes

DBN                 object
SchoolName          object
No_AP_TestTakers    object
Total_Exam_Taken    object
No_Exam_Passed      object
SAT_Math_Score       int64
dtype: object

In [7]:
from sklearn.linear_model import LinearRegression

In [64]:
#Model 1 :

In [21]:
lm = LinearRegression()
lm

LinearRegression()

In [22]:
df['SAT_Math_Score'] = df['SAT_Math_Score'].astype(str).str.replace(',', '', regex=False).astype(float)
df['No_AP_TestTakers'] = df['No_AP_TestTakers'].astype(str).str.replace(',', '', regex=False).astype(float)
df['Total_Exam_Taken'] = df['Total_Exam_Taken'].astype(str).str.replace(',', '', regex=False).astype(float)

In [23]:
#For the above lines, I did them because of an error : 'ValueError: could not convert string to float: '1,510' when I tried to fit X and Y
#The lines above convert the values to strings, then removes the commas, then converts them to float. This way the lm.fit(X,Y) works

In [24]:
Y = df['SAT_Math_Score']
X = df[['No_AP_TestTakers', 'Total_Exam_Taken']]

In [25]:
print(df[['No_AP_TestTakers', 'Total_Exam_Taken', 'SAT_Math_Score']].dtypes)


No_AP_TestTakers    float64
Total_Exam_Taken    float64
SAT_Math_Score      float64
dtype: object


In [26]:
lm.fit(X,Y)

LinearRegression()

In [27]:
lm.intercept_

np.float64(421.45569422966344)

In [28]:
lm.coef_

array([ 0.23505716, -0.03284627])

In [29]:
Yprt = lm.predict(X)

In [30]:
from sklearn.metrics import mean_squared_error
mean_squared_error(Y,Yprt)

3565.6112371183126

In [31]:
#Model 2 :

In [42]:
df['No_Exam_Passed'] = df['No_Exam_Passed'].astype(str).str.replace(',', '', regex=False).astype(float)


In [43]:
Y2 = df['SAT_Math_Score']
X2 = df[['No_AP_TestTakers', 'Total_Exam_Taken', 'No_Exam_Passed']]

In [44]:
lm2 = LinearRegression()
lm2
lm2.fit(X2,Y2)

LinearRegression()

In [45]:
lm2.intercept_

np.float64(429.41248253218225)

In [46]:
lm2.coef_

array([ 0.55497041, -0.41160723,  0.257457  ])

In [47]:
Y2prt = lm2.predict(X2)

In [48]:
from sklearn.metrics import mean_squared_error
mean_squared_error(Y2,Y2prt)

3128.046958490197

In [51]:
#Set 4 : The model using the 3 independent variables is the better variable because it's MSE (3128) was lower than that
#of the model using only the 'No_AP_TestTakers' and 'Total_Exam_Taken' (3565)

In [52]:
#Set 5 : Using the testing.csv file

In [57]:
from google.colab import files
uploaded = files.upload()

Saving testing.csv to testing (1).csv


In [58]:
filename2 = list(uploaded.keys())[0]

In [59]:
df2 = pd.read_csv(filename2)

In [60]:
df2

DBN                                        SCHOOL NAME  \
0    01M448                UNIVERSITY NEIGHBORHOOD HIGH SCHOOL   
1    01M515            LOWER EAST SIDE PREPARATORY HIGH SCHOOL   
2    01M539  NEW EXPLORATIONS INTO SCIENCE, TECHNOLOGY AND ...   
3    02M300  URBAN ASSEMBLY SCHOOL OF DESIGN AND CONSTRUCTI...   
4    02M305  URBAN ASSEMBLY ACADEMY OF GOVERNMENT AND LAW, THE   
..      ...                                                ...   
169  31R605                STATEN ISLAND TECHNICAL HIGH SCHOOL   
170  32K403               ACADEMY FOR ENVIRONMENTAL LEADERSHIP   
171  32K552                          ACADEMY OF URBAN PLANNING   
172  32K554               ALL CITY LEADERSHIP SECONDARY SCHOOL   
173  32K556  BUSHWICK LEADERS HIGH SCHOOL FOR ACADEMIC EXCE...   

     No_AP_TestTakers  Total_Exam_Taken  No_Exam_Passed  SAT_Math_Score  
0                  37                53              21             423  
1                  50                60              54             557  
2                 306               587             323             574  
3                 135               135               8             449  
4                  31                40              20             388  
..                ...               ...             ...             ...  
169               595              1098             977             682  
170                27                47               6             366  
171                36                43              20             364  
172                24                43              16             465  
173                39                44              19             358  

[174 rows x 6 columns]

In [61]:
df2.dtypes

DBN                 object
SCHOOL NAME         object
No_AP_TestTakers     int64
Total_Exam_Taken     int64
No_Exam_Passed       int64
SAT_Math_Score       int64
dtype: object

In [71]:
#Model 1 testing :

In [72]:
lm3 = LinearRegression()
lm3


LinearRegression()

In [73]:
testY = df2['SAT_Math_Score']
testX = df2[['No_AP_TestTakers', 'Total_Exam_Taken']]

In [74]:
lm3.fit(testX, testY)

LinearRegression()

In [75]:
lm3.intercept_

np.float64(422.3729301001348)

In [76]:
lm3.coef_

array([0.07770456, 0.04409442])

In [77]:
testYprt = lm3.predict(testX)

In [78]:
from sklearn.metrics import mean_squared_error
mean_squared_error(testY,testYprt)

3453.4040615323333

In [79]:
#Testing model 2 :

In [94]:
lm4 = LinearRegression()
lm4

LinearRegression()

In [95]:
testY2 = df2['SAT_Math_Score']
testX2 = df2[['No_AP_TestTakers', 'Total_Exam_Taken', 'No_Exam_Passed']]

In [96]:
lm4.fit(testX2, testY2)

LinearRegression()

In [97]:
lm4.intercept_

np.float64(426.93522434120615)

In [98]:
lm4.coef_

array([ 0.29180085, -0.21238267,  0.18033367])

In [99]:
testY2prt = lm4.predict(testX2)

In [100]:
from sklearn.metrics import mean_squared_error
mean_squared_error(testY2,testY2prt)

3229.362308717022

In [102]:
#The better model is still the model with the 3 independent variables because even after the testing data,
#The MSE of the 3 independent variables (3229) is still lower than that of the 'No_AP_TestTakers' and 'Total_Exam_Taken' (3453)